# Generated by Django 3.0.2 on 2021-01-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='URL',
            field=models.TextField(default='url', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
